### ISSUE TITLE
Please provide a sample for using the nodejs with uwp

### ISSUE THREAD

**Issue by abhisheksaatal** [Microsoft/node-uwp#10]
Hi,

Its nice to know that nodejs is supported uwp, Can you please provide a use case sample. so that i can know what we can achieve with this.

Regards,
Abhishek Saatal

**Comment by jianchun** [comment]
@abhisheksaatal Apologize for late response. There is a trivial sample in http://ms-iot.github.io/content/en-US/win10/samples/NodejsWU.htm (under "Universal Windows Platform (UWP) namespaces"). Generally this gives your app access to the UWP API.
