### ISSUE TITLE
Using this without visual studio

### ISSUE THREAD

**Issue by TrevorDev** [Microsoft/node-uwp#15]
Is it planned to be able to use this without the requirement of visual studio? Visual studio is very large and feels like overkill when I want to write a quick node script. I am use to using node with typescript and plugins that only work in the atom editor and it seems I need to learn a new workflow just to use windows api's in node.

When I want to use any open source library I can just npm install it. When I want to use windows API's i need to install a custom version of node, 10gb of visual studio and use Microsoft tools to build. This causes me a lot of friction.

**Comment by jianchun** [comment]
@TrevorDev "Visual Studio" requirement here is mainly for building node native addon modules, as this is a native addon module written in C++ and distributed as source. I have heard that node has been looking at alternative official approaches for distributing native addon modules. Maybe in future we no longer need it.

On the other hand, this module might not be very useful for console scripts, as the Windows APIs supported are very limited outside of UWP context. This module is primarily to expose UWP APIs to [Node.js on Windows IoT](https://github.com/ms-iot/ntvsiot).

**Comment by TrevorDev** [comment]
I guess this module just isn't what I am looking for. I am wanting to work with the mediacapture api's to access the webcam but I am just not very happy with the visual studio experience as I find it too slow to compile and debug my applications compared to my existing workflow with node. Please let me know if you know of any tools that may be able to help me.

Thanks.

**Comment by jianchun** [comment]
@TrevorDev Thanks for your feedback! We'll take note on your scenario.
