### ISSUE TITLE
how close are we to being able to use Chakra for all our nodejs apps as a choice

### ISSUE THREAD

**Issue by xtianus79** [Microsoft/node-uwp#7]
this looks awesome and should not just be for iot development.  When can we start using this mainstream for performance gains?  also, what git repo should we specifically be watching for updates.  All these repos are a bit confusing to follow.

**Comment by kunalspathak** [comment]
@xtianus79 , For node+chakra work goes in Microsoft/node, "chnext" branch. Currently it is based on node0.12 and we will soon update it to support latest node6.0 with chakra.dll shipped with latest windows 10.10586.
